### ISSUE TITLE
Theme wont apply?

### ISSUE THREAD

**Issue by panicthescaredycat** [FivePixels/Tidal#1]
I need some help, So I open the config on Spicetify, to direct it to Tidal... after I do Spicetify backup apply, and then Spicetify auto, It doesn't apply a theme, it just open spotify with the basic regular theme... Any idea why?

**Comment by panicthescaredycat** [comment]
I guess it's not updated to V2 standards? Or idk.. Theme just stopped working.. i've tried everything.. :/

**Comment by FivePixels** [comment]
It seems to be applying for me. Can you send your config file?

**Comment by panicthescaredycat** [comment]
There's the config..

and this is what my Spotify looks life when I tried applying it x.x

![Untitled](https://user-images.githubusercontent.com/67936666/119278861-e25ee080-bbdc-11eb-8fd3-6889193b246a.png)


[config.zip](https://github.com/FivePixels/Tidal/files/6529026/config.zip)

**Comment by FivePixels** [comment]
Join the Spicetify Discord and I can help you with it there. https://discord.gg/PHPz4yw3Yp
